### ISSUE TITLE
你好我想问下Launcher 已经是全屏了，为什么给launcher.xml 根布局，设置背景，依然全屏不了

### ISSUE THREAD

**Issue by chongbo2013** [PeterCxy/telegram-bot-coffee#1]
你好我想问下Launcher 已经是全屏了，为什么给launcher.xml 根布局，设置背景，依然全屏不了，老是padingTop一个状态栏的高度，请你您是如何解决 LightLauncher里的这个问题呢。 Thanku

**Comment by PeterCxy** [comment]
哥哥，提交issue请看看清楚地方
