### ISSUE TITLE
parser.parse problems with some input.

### ISSUE THREAD

**Issue by Artoria2e5** [PeterCxy/telegram-bot-coffee#2]
``` CoffeeScript
a='"foo "bar  " baz'
console.log a.split ' ' # Array [ '"foo', '"bar', '', '"', 'baz' ]
console.log parse a # Array [ ], !!!
# Expected: Array [ 'foo "bar  ', 'baz' ]
```

**Comment by PeterCxy** [comment]
Fix it recently.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.2.7&pv=5.1.1] On Wed, Aug 19, 2015 at 3:44 PM, Mingye Wang < notifications@github.com [notifications@github.com] > wrote:
a='"foo "bar  " baz'console.log a.split ''# Array [ '"foo', '"bar', '', '"', 'baz' ]console.log parse a # Array [ ], !!!# Expected: Array [ 'foo "bar  ', 'baz' ]
